version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "github_actions"
      - "type::chore"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "javascript"
      - "type::chore"
