name: 'Wait For'
description: 'Wait for checks on a ref to complete successfully'
author: 'Replicated'
inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  ref:
    description: 'The ref to wait for'
    required: false
    default: ${{ github.ref }}
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: '600'
  interval:
    description: 'Polling interval in seconds'
    required: false
    default: '10'
  check-name:
    description: 'Check name to wait for. Overrids check-regexp if both are set'
    required: false
    default: ''
  check-regexp:
    description: 'Check name regexp to wait for'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
